/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_edma.h"
#include "fsl_dmamux.h"
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_ftm.h"
#include "fsl_dspi.h"
#include "fsl_dspi_edma.h"
#include "fsl_adc16.h"
#include "fsl_i2c.h"
#include "fsl_gpio.h"
#include "fsl_port.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* Used DMA device. */
#define DMA_DMA_BASEADDR DMA0
/* Associated DMAMUX device that is used for muxing of requests. */
#define DMA_DMAMUX_BASEADDR DMAMUX
/* Definition of peripheral ID */
#define FTM3_PERIPHERAL FTM3
/* Definition of the clock source frequency */
#define FTM3_CLOCK_SOURCE 60000000UL
/* Definition of the clock source frequency */
#define FTM3_TIMER_MODULO_VALUE 37499
/* FTM3 interrupt vector ID (number). */
#define FTM3_IRQN FTM3_IRQn
/* FTM3 interrupt handler identifier. */
#define FTM3_IRQHANDLER FTM3_IRQHandler
/* Definition of FTM3 channel/pair number 6 on Edge-aligned PWM */
#define FTM3_FTM_SERVO0_CHANNEL kFTM_Chnl_6
/* BOARD_InitPeripherals defines for SPI0 */
/* Definition of peripheral ID */
#define SPI0_PERIPHERAL SPI0
/* Definition of the clock source */
#define SPI0_CLOCK_SOURCE DSPI0_CLK_SRC
/* Definition of the clock source frequency */
#define SPI0_CLK_FREQ CLOCK_GetFreq(SPI0_CLOCK_SOURCE)
/* SPI0 eDMA source request. */
#define SPI0_RX_DMA_REQUEST kDmaRequestMux0SPI0Rx
/* Selected eDMA channel number. */
#define SPI0_RX_DMA_CHANNEL 5
/* DMAMUX device that is used for muxing of the request. */
#define SPI0_RX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define SPI0_RX_DMA_BASEADDR DMA0
/* Selected eDMA channel number. */
#define SPI0_INTERMEDIARY_DMA_CHANNEL 2
/* Used DMA device. */
#define SPI0_INTERMEDIARY_DMA_BASEADDR DMA0
/* SPI0 eDMA source request. */
#define SPI0_TX_DMA_REQUEST kDmaRequestMux0SPI0Tx
/* Selected eDMA channel number. */
#define SPI0_TX_DMA_CHANNEL 1
/* DMAMUX device that is used for muxing of the request. */
#define SPI0_TX_DMAMUX_BASEADDR DMAMUX
/* Used DMA device. */
#define SPI0_TX_DMA_BASEADDR DMA0
/* Alias for ADC0 peripheral */
#define ADC0_PERIPHERAL ADC0
/* Definition of custom name for ADC0 configuration #0 (channel 14, control group 0) */
#define ADC0_MOTOR_BEMF1_A_IRQ_CHANNEL 0U
/* Definition of custom name for ADC0 configuration #1 (channel 17, control group 0) */
#define ADC0_MOTOR_BEMF1_B_IRQ_CHANNEL 1U
/* Definition of custom name for ADC0 configuration #2 (channel 18, control group 0) */
#define ADC0_MOTOR_BEMF1_C_IRQ_CHANNEL 2U
/* Definition of custom name for ADC0 configuration #3 (channel 19, control group 0) */
#define ADC0_MOTOR_BEMF_STAR_CHANNEL 3U
/* Definition of custom name for ADC0 configuration #4 (channel 12, control group 0) */
#define ADC0_MOTOR_BEMF10_A_IRQ_CHANNEL 4U
/* Definition of custom name for ADC0 configuration #5 (channel 13, control group 0) */
#define ADC0_MOTOR_BEMF10_B_IRQ_CHANNEL 5U
/* Definition of custom name for ADC0 configuration #6 (channel 23, control group 0) */
#define ADC0_MOTOR_BEMF10_C_IRQ_CHANNEL 6U
/* ADC0 interrupt vector ID (number). */
#define ADC0_IRQN ADC0_IRQn
/* ADC0 interrupt handler identifier. */
#define motor_bemf_irq_handler ADC0_IRQHandler
/* Channel 0 (SE.14) conversion control group. */
#define ADC0_CH0_CONTROL_GROUP 0
/* Channel 1 (SE.17) conversion control group. */
#define ADC0_CH1_CONTROL_GROUP 0
/* Channel 2 (SE.18) conversion control group. */
#define ADC0_CH2_CONTROL_GROUP 0
/* Channel 3 (SE.19) conversion control group. */
#define ADC0_CH3_CONTROL_GROUP 0
/* Channel 4 (SE.12) conversion control group. */
#define ADC0_CH4_CONTROL_GROUP 0
/* Channel 5 (SE.13) conversion control group. */
#define ADC0_CH5_CONTROL_GROUP 0
/* Channel 6 (SE.23) conversion control group. */
#define ADC0_CH6_CONTROL_GROUP 0
/* Definition of peripheral ID */
#define FTM0_PERIPHERAL FTM0
/* Definition of the clock source frequency */
#define FTM0_CLOCK_SOURCE 60000000UL
/* Definition of the clock source frequency */
#define FTM0_TIMER_MODULO_VALUE 749
/* Definition of FTM0 channel number 0 */
#define FTM0_MOTOR_A_FTM0_CH0_CHANNEL kFTM_Chnl_0
/* Definition of FTM0 channel number 1 */
#define FTM0_MOTOR_B_FTM0_CH1_CHANNEL kFTM_Chnl_1
/* Definition of FTM0 channel number 2 */
#define FTM0_MOTOR_C_FTM0_CH2_CHANNEL kFTM_Chnl_2
/* Alias for ADC1 peripheral */
#define ADC1_PERIPHERAL ADC1
/* Definition of custom name for ADC1 configuration #0 (channel 10, control group 0) */
#define ADC1_CAMERA_ADC1_SE10 0U
/* Definition of custom name for ADC1 configuration #1 (channel 19, control group 0) */
#define ADC1_POT_CHANNEL 1U
/* Definition of custom name for ADC1 configuration #2 (channel 0, control group 0) */
#define ADC1_POT_CHANNEL_BLK 2U
/* ADC1 interrupt vector ID (number). */
#define ADC1_IRQN ADC1_IRQn
/* ADC1 interrupt handler identifier. */
#define ADC1_IRQHANDLER ADC1_IRQHandler
/* Channel 0 (SE.10) conversion control group. */
#define ADC1_CH0_CONTROL_GROUP 0
/* Channel 1 (SE.19) conversion control group. */
#define ADC1_CH1_CONTROL_GROUP 0
/* Channel 2 (SE.0) conversion control group. */
#define ADC1_CH2_CONTROL_GROUP 0
/* Definition of peripheral ID */
#define FTM1_PERIPHERAL FTM1
/* Definition of the clock source frequency */
#define FTM1_CLOCK_SOURCE 60000000UL
/* Definition of the clock source frequency */
#define FTM1_TIMER_MODULO_VALUE 2999
/* FTM1 interrupt vector ID (number). */
#define FTM1_IRQN FTM1_IRQn
/* FTM1 interrupt handler identifier. */
#define FTM1_IRQHANDLER FTM1_IRQHandler
/* Definition of FTM1 channel/pair number 0 on Edge-aligned PWM */
#define FTM1_CAMERA1_CHANNEL kFTM_Chnl_0
/* BOARD_InitPeripherals defines for I2C0 */
/* Definition of peripheral ID */
#define I2C0_PERIPHERAL I2C0
/* Definition of the clock source */
#define I2C0_CLOCK_SOURCE I2C0_CLK_SRC
/* Definition of the clock source frequency */
#define I2C0_CLK_FREQ CLOCK_GetFreq(I2C0_CLOCK_SOURCE)
/* I2C0 interrupt vector ID (number). */
#define I2C0_IRQN I2C0_IRQn
/* I2C0 interrupt handler identifier. */
#define I2C0_IRQHANDLER I2C0_IRQHandler
/* Alias for GPIOD peripheral */
#define GPIOD_GPIO GPIOD
/* Alias for PORTD */
#define GPIOD_PORT PORTD
/* GPIOD interrupt vector ID (number). */
#define GPIOD_IRQN PORTD_IRQn
/* GPIOD interrupt handler identifier. */
#define GPIOD_IRQHANDLER PORTD_IRQHandler
/* Alias for GPIOC peripheral */
#define GPIOC_GPIO GPIOC
/* Alias for PORTC */
#define GPIOC_PORT PORTC
/* GPIOC interrupt vector ID (number). */
#define GPIOC_IRQN PORTC_IRQn
/* GPIOC interrupt handler identifier. */
#define GPIOC_IRQHANDLER PORTC_IRQHandler

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const edma_config_t DMA_config;
extern const ftm_config_t FTM3_config;
extern const dspi_master_config_t SPI0_config;
extern edma_handle_t SPI0_RX_Handle;
extern edma_handle_t SPI0_Intermediary_Handle;
extern edma_handle_t SPI0_TX_Handle;
extern dspi_master_edma_handle_t kuruma_spi0_edma_handle;
extern adc16_channel_config_t ADC0_channelsConfig[7];
extern const adc16_config_t ADC0_config;
extern const adc16_channel_mux_mode_t ADC0_muxMode;
extern const ftm_config_t FTM0_config;
extern adc16_channel_config_t ADC1_channelsConfig[3];
extern const adc16_config_t ADC1_config;
extern const adc16_channel_mux_mode_t ADC1_muxMode;
extern const ftm_config_t FTM1_config;
extern const i2c_master_config_t I2C0_config;

/***********************************************************************************************************************
 * Callback functions
 **********************************************************************************************************************/
/* DSPI eDMA callback function for the SPI0 component (init. function BOARD_InitPeripherals)*/
extern void kuruma_spi0_edma_handler(SPI_Type *, dspi_master_edma_handle_t *, status_t, void *);

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
